name: Build

on:
  push:
    branches: [ algoxy ]
  pull_request:
    branches: [ algoxy ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Before build
        run: |
          sed -i 's/SimSun/Noto Serif CJK SC/; s/SimHei/Noto Sans CJK SC/; s/Consolas/FreeMono/' prelude.sty
      - name: Build
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add --update pkgconfig make graphviz graphviz-dev imagemagick font-noto-cjk ttf-freefont
            make
      - name: After build
        run: |
          export GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          mv algoxy-en.pdf "algoxy-en-$GIT_HASH.pdf"
          mv algoxy-zh-cn.pdf "algoxy-zh-cn-$GIT_HASH.pdf"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: algoxy
          path: algoxy-*.pdf
